# Generated by Django 4.2.11 on 2024-04-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=100)),
                ('played', models.CharField(max_length=100)),
                ('wins', models.CharField(max_length=100)),
                ('draw', models.CharField(max_length=100)),
                ('losses', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='GoalScorer',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
