# Generated by Django 4.2.11 on 2024-04-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0002_table_remove_player_team_delete_goalscorer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='goal_diff',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
