# Generated by Django 4.2.11 on 2024-04-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0003_table_goal_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='draw',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='played',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
