# Generated by Django 4.2.11 on 2024-04-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0004_alter_table_draw_alter_table_losses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='BplMatch',
        ),
        migrations.RenameModel(
            old_name='Table',
            new_name='BplTable',
        ),
    ]
