# Generated by Django 4.2.11 on 2024-04-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaligaMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=100)),
                ('round_number', models.IntegerField()),
                ('home_team', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=10)),
                ('away_team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaligaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('goal_diff', models.CharField(max_length=100)),
            ],
        ),
    ]
