# Generated by Django 4.2.11 on 2024-06-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brasil_a', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrasilANextMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('round_number', models.IntegerField()),
                ('home_team', models.CharField(max_length=100)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_team', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BrasilAGamesTest',
        ),
    ]
