# Generated by Django 4.2.11 on 2024-06-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brasil_a', '0002_brasilanextmatches_delete_brasilagamestest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brasilanextmatches',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brasilanextmatches',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
